### ISSUE TITLE
hacktoberfest - add circular loader when searching

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#16]
Check out below screenshot of rate shield web ui.

![image](https://github.com/user-attachments/assets/b88276b2-983a-4fb3-8a68-c13e1126f92c)

There is a search button. When search button is clicked input data is sent to an API and search result are updated. I want to show circular loading bar in place of data until searched data is loaded and shown.

**Comment by Vansh-Narang** [comment]
Assign this one to me !!

**Comment by x-sushant-x** [comment]
sure please go ahead

**Comment by x-sushant-x** [comment]
@Vansh-Narang any udpate?

**Comment by x-sushant-x** [comment]
This is completed. Closing this issue.
