### ISSUE TITLE
implement basic sliding window rate limit strategy

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#17]
Basic concept of Rate Shield is to implement different rate limiting strategies and integrate them with Redis. Than user can choose which strategy to apply and what rule to apply on particular API endpoint.

Currently we support: -
1. Token Bucket
2. Fixed Window Counter

You can provide a very basic sliding window rate limiting in golang. There is no need to integrate redis in it as of now.

Procedure: -
1. Fork this repo.
2. Clone into your machine.
3. Add a new file `sliding_window_counter.go` in `rate_shield/limiter` directory.
4. Implement sliding window counter rate limiting logic into that file.

**Comment by monzilnepali** [comment]
@x-sushant-x Can I take look on this issue?

**Comment by x-sushant-x** [comment]
sure. please go ahead.

**Comment by x-sushant-x** [comment]
I'm assigning this to you. Feel free to ask if you need more help.

**Comment by x-sushant-x** [comment]
As there is no update from @monzilnepali this issue is open for everyone.

**Comment by x-sushant-x** [comment]
Done via https://github.com/x-sushant-x/Rate-Shield/commit/4ad511a466baf3e616046be4be559b051062cf92
