### ISSUE TITLE
hacktoberfest - implement basic leaky bucket rate limit strategy

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#18]
Basic concept of Rate Shield is to implement different rate limiting strategies and integrate them with Redis. Than user can choose which strategy to apply and what rule to apply on particular API endpoint.

Currently we support: -
1. Token Bucket
2. Fixed Window Counter

You can provide code for very basic leaky bucket rate limiting strategy in golang. There is no need to integrate redis in it as of now.

Procedure: -
1. Fork this repo.
2. Clone into your machine.
3. Add a new file `leaky_bucket.go` in `rate_shield/limiter` directory.
4. Implement leaky bucket rate limiting logic into that file.

**Comment by anveshthakur** [comment]
hi @x-sushant-x, Can I work on this issue?

**Comment by uskYash** [comment]
Hi , I hope you're doing well. I I believe I can contribute effectively, and I'm eager to help resolve it. If it's possible, could you please assign me this task? I would really appreciate the opportunity. Thank you!"

**Comment by x-sushant-x** [comment]
Hi @anveshthakur I'm assigning this issue to you. Also @uskYash please check other issues in this repo, you can work on them.

**Comment by x-sushant-x** [comment]
@anveshthakur any update?

**Comment by anveshthakur** [comment]
This was done way back @x-sushant-x, right? 


Attaching PR for your reference -
https://github.com/x-sushant-x/Rate-Shield/pull/31

**Comment by x-sushant-x** [comment]
Yes My Bad
