### ISSUE TITLE
hacktoberfest - add example on how to use Rate Shield with GoFiber.

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#19]
Go through this [documentation](https://github.com/x-sushant-x/Rate-Shield/tree/main/rate_shield/documentation) and learn how Rate Shield work.

After that write a middleware program using GoFiber showing and example of using Rate Shield. In short you have to make a basic application using Go Fiber that sends `ip` and `endpoint` to Rate Shield `/check-limit` API. If Rate Shield responded with `200` status code you can pass on and it it responded with `429` status code you can drop that request and send back `429` status code to client.

Please write this code in `/rate_sheild/examples`

**Comment by deexithparand** [comment]
Hi @x-sushant-x, can I work on this issue too

**Comment by x-sushant-x** [comment]
@deexithparand yes you can
