### ISSUE TITLE
hacktoberfest - add example on how to use Rate Shield with Gin

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#20]
Go through this [documentation](https://github.com/x-sushant-x/Rate-Shield/tree/main/rate_shield/documentation) and learn how Rate Shield works.

After that write a middleware program using Gin showing an example of using Rate Shield. In short you have to make a basic application using Go Fiber that sends `ip` and `endpoint` to Rate Shield `/check-limit` API. If Rate Shield responds with `200` status code you can pass and if it responds with `429` status code you can drop that request and send back `429` status code to the client.

Please write this code in `/rate_sheild/examples`

**Comment by rogueloop** [comment]
Can I get assigned for this

**Comment by x-sushant-x** [comment]
Sure! please go ahead

**Comment by rogueloop** [comment]
Sorry to inform I won't be working on this, something with more personal priority came up.

**Comment by x-sushant-x** [comment]
Okay No Issues!

**Comment by deexithparand** [comment]
Hi @x-sushant-x, Can I work on this issue

**Comment by x-sushant-x** [comment]
Yes you can @deexithparand

**Comment by x-sushant-x** [comment]
Hi @deexithparand you are still working on this too, right?

**Comment by deexithparand** [comment]
Hi @x-sushant-x, I am still working on this one too. I'll update once this is done

**Comment by x-sushant-x** [comment]
cool

**Comment by x-sushant-x** [comment]
Hey @deexithparand any update?

**Comment by deexithparand** [comment]
Hi @x-sushant-x, I got caught up with some other work, so I couldn’t work on this yet. I’ll complete the PR by tomorrow EOD and keep you updated.

**Comment by x-sushant-x** [comment]
Sure No issue.

**Comment by x-sushant-x** [comment]
@deexithparand hi!. Is there any update for me?

**Comment by deexithparand** [comment]
Hi @x-sushant-x,
Apologies for the delay on this. I've been caught up with a personal project and couldn't make progress on this issue. Please feel free to unassign it from me. I'll definitely contribute to your repo when I have more availability. Sorry for not updating you earlier!

**Comment by x-sushant-x** [comment]
Sure @deexithparand no issues!
