### ISSUE TITLE
refactor code for `fixed_window_counter.go` using clean code principles

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#25]
File Location: `rate_shield/limiter/fixed_window_counter.go`

This file contain code for `Fixed Window Counter` rate limiting strategy and its integration with `Redis`. Task is to refactor this code using clean code principles.

### Expected Changes:
* Shorter functions.
* Single Responsibility Principle.

2 functions of this file `processRequest` and `spawnNewFixedWindow` are very big in size. You have to break them in smaller functions without affecting existing logic.

**Comment by arrlancore** [comment]
I would like to work on this issue @x-sushant-x

**Comment by x-sushant-x** [comment]
Yes please go ahead

**Comment by x-sushant-x** [comment]
Yes! Please go ahead.
