### ISSUE TITLE
auto refresh rules list when a rule is created, updated or deleted - `TypeScript & React`

### ISSUE THREAD

**Issue by x-sushant-x** [x-sushant-x/Rate-Shield#30]
In Rate Shield web ui we can create, delete and edit rules. When any of this action is performed I want rules list to refresh automatically. Currently it do not show updated data until manual reload is done.

**Comment by Manik072** [comment]
Can you please assign this to me? I prefer using ContextAPI for this to keep things simple.

**Comment by x-sushant-x** [comment]
completed via https://github.com/x-sushant-x/Rate-Shield/commit/6b6554dce8a6c7225a2f040c2a34a70780725f16
