### ISSUE TITLE
ci: Add a CI for TypeScript code

### ISSUE THREAD

**Issue by Pradumnasaraf** [x-sushant-x/Rate-Shield#39]
Similar to Golang issue #38, there is no CI run on Pull Requests to check for build and Linting for incoming TypeScript code. 

Let me know if you are interested and if can I help with the addition.

**Comment by x-sushant-x** [comment]
@Pradumnasaraf yes! Please go ahead.

**Comment by Pradumnasaraf** [comment]
Thanks. I have raised the PR.
